version: '3.8'
volumes:
  db-data:
  jenkins-store:

services:
  db:
    image: mysql:8.1.0
    container_name: mysql
    #    user: root:root
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cardManagement
      # MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQLDATA: /tmp/db/data
    volumes:
      - db-data:/tmp/db/data
    ports:
      - "3307:3306"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512m"

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    volumes:
      - jenkins-store:/tmp/jenkin
    ports:
      - "8085:8080"
      - "50001:50001"





